### ISSUE TITLE
Problem with Packager

### ISSUE THREAD

**Issue by andrebargas** [ExCiteS/Sapelli#109]
Hello
I'm trying to use yours Sappeli packager to build a simple solution but i'm getting errors when I execute the packager .jar file. I've already tried all the three versions but i'm getting the same error. 
When i try :
`$ java -jar Sapelli\ Packager\ v1.0.3.jar`
I'm getting : 
`Error: Could not find or load main class uk.ac.ucl.excites.sapelli.packager.Packager`

I didn't get it if i have to use another command or i may be missing something. I would be extremely grateful if some one could give me a light.

ps.
I've tried on windows too

**Comment by michalis-vitos** [comment]
Hi @andrebargas,

That is very strange, since the command you are using is correct and you are not missing something.

I suppose you downloaded the Packager from this [link](https://github.com/ExCiteS/Sapelli/releases/tag/Packager-v1.0.3) and you didn't build it on your own from the sources. 

Also, what is your operating system? On Windows, there is an executable (.exe) file that should work by just double clicking on it and you don't need to run any commands. If you have easy access to a Windows machine, can you please try the executable and let me know if you are facing the same issue?

**Comment by andrebargas** [comment]
Hello again @michalis-vitos, thank you for the quickly reply.
Yes, I've downloaded from this same link.
I tried the on Ubuntu 16.04 with open jdk version "1.8.0_181",  and on windows 8 OS. On the windows when i double click, it just create a folder named logs with two empty .txt files, and after that nothing happens...
Should i try in another OS ? Does it have another requirement then Java?

**Comment by michalis-vitos** [comment]
The packager has no other requirement than Java. I assume that your Windows installation has Java installed. It is very strange that your log files are empty, they should at least capture something.

Can you please try to unzip the jar file and check if you are having the class that is supposed to be missing (uk.ac.ucl.excites.sapelli.packager.Packager)?

Also, I suggest you have a look at the following link with similar issues:
https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean

**Comment by jppgomes** [comment]
Hello, i have the same problem @andrebargas  @michalis-vitos

**Comment by matheusbsilva** [comment]
I have the following error:
```
Error: Could not find or load main class uk.ac.ucl.excites.sapelli.packager.Packager
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

I'm using Arch Linux, I installed the javafx package but still don't work.

**Comment by michalis-vitos** [comment]
Hi @matheusbsilva , @jppgomes & @andrebargas ,

Your issues seem to be related to the wrong **Java** installation. I tried to run the Packager on a Live installation of Ubuntu 18 and of course it didn't work, because the OS was missing the Java installation. I then tried to install **OpenJDK 8**, which gave the errors that you describe. Then I followed these steps to install the **Oracle JDK**:

```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
```

The above commands installed Java & the javafx packages. After that, a simple `java -jar Sapelli\ Packager\ v1.0.3.jar` opened the Packager without any issue. So please try to install Java and let me know if you are still facing any issues.

**Comment by andrebargas** [comment]
Hi @michalis-vitos,
Thank you some much for your help and for the quick answers, it seems to be working fine now. IMHO you guys should consider about putting these instruction to prevent other users like me, since these package its not the linux default JDK.
