### ISSUE TITLE
ProjectManagerFragment.java line 97

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#38]
#### in uk.ac.ucl.excites.sapelli.collector.fragments.ProjectManagerFragment.addChild

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/56376727f5d3a7f76b43b5c1](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/56376727f5d3a7f76b43b5c1)

**Comment by mstevens83** [comment]
This crash happened on beta 16, not 15 (as crashlytics seems to think):
```
BUILD_INFO
Built on 2015-09-24T23:34:24-04:00 by mstevens using master branch, revision 5a78ae5 without changes
VERSION_INFO
Sapelli Collector v2.0.0-beta-16 [versionCode: 32709; release]
 SAPELLI_DEVICE_ID_CRC32
1267464168
SAPELLI_DEVICE_ID_MD5
50933394471048853077304065447622148130
```

**Comment by mstevens83** [comment]
This crash is caused by the following `IllegalStateException`:
```Can not perform this action after onSaveInstanceState```

It can be reproduced by exiting/hiding the activity during project reload. Hiding the activity causes `onSaveInstanceState()` to be called before the the `ReloadProjectTask` finishes. When it does finish `setCurrentProject()` gets called, which in turn -- at least in the beta16 code -- caused all tab fragments to be recreated, including the `ExportTabFragment` which calls `addChild()` on itself, which in turns ends op calling `android.support.v4.app.FragmentTransaction.commit()`, which is illegal after the call to `onSaveInstanceState()`.

This particular crash is reproducible on beta16 code (5a78ae5d589978444b57288fe40db653ed5ce83c), but no longer on the current master branch. The reason is that since 42c2f04d6981292c4edf3bc8cdfb0c335cd92deb we no longer recreate the `ProjectManagerTabFragmentPagerAdapter` and tab instances upon project switching/reloading.
So essentially this problem is fixed.

**Comment by mstevens83** [comment]
To avoid similar problems in the future we could make  `ProjectManagerFragment#addChild()` call `android.support.v4.app.FragmentTransaction#commitAllowingStateLoss()` instead of `android.support.v4.app.FragmentTransaction#commit()`. As far as I've been able to test this does not have adverse consequences -- probably because the `ProjectManagerActivity` doesn't (explicitly) rely on saving and reusing its state.

**Comment by mstevens83** [comment]
Since 9909573  `ProjectManagerFragment#addChild()` calls `android.support.v4.app.FragmentTransaction#commitAllowingStateLoss()` instead of `android.support.v4.app.FragmentTransaction#commit()`.
